/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/car": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List cars matching the given filters */
    get: operations["getCars"];
    put?: never;
    /** Register a car */
    post: operations["createCar"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/car/{carId}/rentals": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List a car's current and upcoming bookings */
    get: operations["bookings"];
    put?: never;
    /** Rent a car for a range of whole days */
    post: operations["rent"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/auth/register": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["register"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/auth/login": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["login"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/rentals": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List the signed-in user's rentals, newest first */
    get: operations["mine"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/car/{carId}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get one car by id */
    get: operations["getCarById"];
    put?: never;
    post?: never;
    /** Delete a car by id */
    delete: operations["deleteById"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/auth/me": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["me"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    CreateCarRequest: {
      model: string;
      /** Format: int32 */
      year: number;
      registrationNumber: string;
      vin: string;
      /** Format: int32 */
      seats: number;
      /** Format: int32 */
      doors: number;
      pricePerDay: number;
      /** @enum {string} */
      type: "SUV" | "SEDAN" | "VAN";
    };
    Car: {
      /** Format: int64 */
      id?: number;
      model: string;
      /** Format: int32 */
      year: number;
      registrationNumber: string;
      vin: string;
      /** Format: int32 */
      seats: number;
      /** Format: int32 */
      doors: number;
      pricePerDay: number;
      /** @enum {string} */
      status: "AVAILABLE" | "RENTED";
      /** @enum {string} */
      type: "SUV" | "SEDAN" | "VAN";
    };
    CreateRentalRequest: {
      /** Format: date */
      startDate: string;
      /** Format: date */
      endDate: string;
    };
    RentalView: {
      /** Format: int64 */
      id: number;
      /** Format: int64 */
      carId: number;
      carModel: string;
      registrationNumber: string;
      /** Format: date */
      startDate: string;
      /** Format: date */
      endDate: string;
      totalPrice: number;
    };
    RegisterRequest: {
      /** Format: email */
      email: string;
      password: string;
    };
    CurrentUser: {
      email: string;
      roles: string[];
    };
    LoginRequest: {
      email: string;
      password: string;
    };
    PageMetadata: {
      /** Format: int64 */
      size?: number;
      /** Format: int64 */
      number?: number;
      /** Format: int64 */
      totalElements?: number;
      /** Format: int64 */
      totalPages?: number;
    };
    PagedModelCar: {
      content?: components["schemas"]["Car"][];
      page?: components["schemas"]["PageMetadata"];
    };
    Booking: {
      /** Format: date */
      startDate: string;
      /** Format: date */
      endDate: string;
      mine: boolean;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  getCars: {
    parameters: {
      query?: {
        q?: string;
        type?: ("SUV" | "SEDAN" | "VAN")[];
        status?: ("AVAILABLE" | "RENTED")[];
        minPrice?: number;
        maxPrice?: number;
        seats?: number[];
        doors?: number[];
        minYear?: number;
        maxYear?: number;
        /** @description Zero-based page index (0..N) */
        page?: number;
        /** @description The size of the page to be returned */
        size?: number;
        /** @description Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported. */
        sort?: string[];
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PagedModelCar"];
        };
      };
    };
  };
  createCar: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateCarRequest"];
      };
    };
    responses: {
      /** @description Created */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Car"];
        };
      };
    };
  };
  bookings: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        carId: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Booking"][];
        };
      };
    };
  };
  rent: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        carId: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateRentalRequest"];
      };
    };
    responses: {
      /** @description Created */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["RentalView"];
        };
      };
    };
  };
  register: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["RegisterRequest"];
      };
    };
    responses: {
      /** @description Created */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CurrentUser"];
        };
      };
    };
  };
  login: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["LoginRequest"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CurrentUser"];
        };
      };
    };
  };
  mine: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["RentalView"][];
        };
      };
    };
  };
  getCarById: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        carId: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Car"];
        };
      };
    };
  };
  deleteById: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        carId: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  me: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CurrentUser"];
        };
      };
    };
  };
}
