/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/car": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List cars matching the given filters */
    get: operations["CarController_getCars"];
    put?: never;
    /** Register a car */
    post: operations["CarController_create"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/car/{carId}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get one car by id */
    get: operations["CarController_getCarById"];
    put?: never;
    post?: never;
    /** Delete a car by id */
    delete: operations["CarController_deleteById"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/users/me": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["UserController_getProfile"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/car/{carId}/rentals": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List a car's current and upcoming bookings */
    get: operations["RentalController_bookings"];
    put?: never;
    /** Rent a car for a range of whole days */
    post: operations["RentalController_rent"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/rentals": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List the signed-in user's rentals, newest first */
    get: operations["RentalController_mine"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/rentals/{rentalId}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /** Cancel one of the signed-in user's upcoming rentals */
    delete: operations["RentalController_cancel"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/rentals/{rentalId}/finish": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Finish one of the signed-in user's active rentals early */
    post: operations["RentalController_finish"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    Car: {
      id: number;
      model: string;
      year: number;
      registrationNumber: string;
      vin: string;
      seats: number;
      doors: number;
      pricePerDay: number;
      /** @enum {string} */
      type: "suv" | "sedan" | "van";
      /**
       * @description Derived: rented while a rental covers today
       * @enum {string}
       */
      status: "available" | "rented";
    };
    PageMetadata: {
      size: number;
      number: number;
      totalElements: number;
      totalPages: number;
    };
    Booking: {
      startDate: string;
      endDate: string;
      mine: boolean;
    };
    RentalView: {
      id: number;
      carId: number;
      startDate: string;
      endDate: string;
      totalPrice: number;
      carModel: string;
      registrationNumber: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  CarController_getCars: {
    parameters: {
      query?: {
        q?: string;
        type?: ("suv" | "sedan" | "van")[];
        status?: ("available" | "rented")[];
        minPrice?: number;
        maxPrice?: number;
        seats?: number[];
        doors?: number[];
        minYear?: number;
        maxYear?: number;
        page?: number;
        size?: number;
        sort?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            content: components["schemas"]["Car"][];
            page: components["schemas"]["PageMetadata"];
          };
        };
      };
    };
  };
  CarController_create: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": {
          model: string;
          year: number;
          registrationNumber: string;
          vin: string;
          seats: number;
          doors: number;
          pricePerDay: number;
          /** @enum {string} */
          type: "suv" | "sedan" | "van";
        };
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            id: number;
            model: string;
            year: number;
            registrationNumber: string;
            vin: string;
            seats: number;
            doors: number;
            pricePerDay: number;
            /** @enum {string} */
            type: "suv" | "sedan" | "van";
            /**
             * @description Derived: rented while a rental covers today
             * @enum {string}
             */
            status: "available" | "rented";
          };
        };
      };
    };
  };
  CarController_getCarById: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        carId: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            id: number;
            model: string;
            year: number;
            registrationNumber: string;
            vin: string;
            seats: number;
            doors: number;
            pricePerDay: number;
            /** @enum {string} */
            type: "suv" | "sedan" | "van";
            /**
             * @description Derived: rented while a rental covers today
             * @enum {string}
             */
            status: "available" | "rented";
          };
        };
      };
    };
  };
  CarController_deleteById: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        carId: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  UserController_getProfile: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            user: {
              id: string;
              email: string;
              name: string;
              /** @enum {string} */
              role: "user" | "admin";
            };
          };
        };
      };
    };
  };
  RentalController_bookings: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        carId: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Booking"][];
        };
      };
    };
  };
  RentalController_rent: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        carId: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": {
          /** Format: date */
          startDate: string;
          /** Format: date */
          endDate: string;
        };
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            id: number;
            carId: number;
            startDate: string;
            endDate: string;
            totalPrice: number;
            carModel: string;
            registrationNumber: string;
          };
        };
      };
    };
  };
  RentalController_mine: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["RentalView"][];
        };
      };
    };
  };
  RentalController_cancel: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        rentalId: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  RentalController_finish: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        rentalId: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": {
          /** Format: date */
          endDate: string;
        };
      };
    };
    responses: {
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
}
