spring:
  application:
    name: api
  datasource:
    url: jdbc:postgresql://localhost:5432/car_rental
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: true
    properties:
      jakarta.persistence.schema-generation:
        scripts:
          action: create
          create-target: build/schema.sql
  data:
    web:
      pageable:
        default-page-size: 20
        max-page-size: 100

server:
  servlet:
    session:
      cookie:
        http-only: true
        same-site: lax
        secure: false

app:
  web-origin: http://localhost:3000
  cookie-domain: ""